FROM ubuntu

# System packages
RUN apt-get clean && apt-get update -y && \
    apt-get install -y python3 python3-pip curl wget unzip procps openjdk-8-jdk && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*
